name: Build and Push Docker Image
on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.0
      - name: Replace Version in version.go
        run: sed -i 's/{development}/${{ github.ref_name }}/' ./internal/common/version.go
      - name: Mkdir dist
        run: mkdir -p ./dist
      - name: Compile Supervisor
        run: go build -o ./dist/supervisor ./cmd/supervisor/main.go
      - name: Compile Satellite
        run: go build -o ./dist/satellite ./cmd/satellite/main.go
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .docker/supervisor/Dockerfile
          push: true
          tags:
            - ${{ secrets.DOCKER_HUB_USERNAME }}/slixx-supervisor:latest
            - ${{ secrets.DOCKER_HUB_USERNAME }}/slixx-supervisor:${{ github.ref_name }}
